rm -rf *.or
rm -rf *.bak
rm -rf *.exe
rm -rf *.ppu
rm -rf *.o
rm -rf *.compiled
rm -rf lib/*
rm -rf backup/
rm -rf src/backup/
rm -rf src/app/wordpress/backup/
rm -rf src/app/wordpress/model/backup/
rm -rf src/app/wordpress/plugins/backup/